tibirna/qgit

src/mainimpl.cpp
When opening a nonexistent directory from the recently used repositories list,
the error message contained a spelling mistake.
Bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851193
=> Fix error message spelling

.gitignore, README, src/mainimpl.cpp
Hi
I noticed that in qgit-2.7 some of the key bindings did not work anymore. Especially n/k (to move down one revision) not working was quite annoing and prevented me from upgrading.
I also adjusted the readme to reflect the current keybindings for going to revisions page (r -> CTRL-r) and to the patch page (p -> CTRL-p). There might be different mismatches, but most keys I did try with the patched versions were doing what I expected.
Thanks and cheers
Urs
=> Fix broken keybindings (i.e. n, k) and adjust Readme to current keybindings

src/mainimpl.cpp
When selecting a branch on the context menu, the action text is supposed to have the ref name in it. In some cases, Qt mangles the text and inserts an ampersand (shortcut marker) on the triggered action (shortcuts are not shown in the UI). I don't know why Qt does this, this seems undocumented behavior. Due to the mangling, the ref obviously can't be found. By using iconText() instead of text(), Qt returns the text with ampersands removed.
As Qt is mangling texts, maybe a better fix would be to set the ref name into the userdata somewhere, but this quick fix works for me. It'll probably break on refnames with ampersands, but they should be rare.
=> Extract ref name from QAction's iconText() instead of text()

.editorconfig
Editor config is a plugin that I use both in vim and visual studio to help me respect whitespace preferences of different projects.
Is it appropriate to commit this file?
=> An editorconfig file.

src/listview.cpp, src/revsview.cpp
This is a regression since 2fed338fd4c8c9bf147beeca7018ff2a946dbfb3.
We can't just clear current file name, because it's useful in some cases. For example if you browse commits for particular file that was selected in the left panel.
As far as I understand the goal is to open "Log" tab when different commit is pressed and open "Diff" tab when different filename is selected. This can be achieved by checking if sha has been changed.
Fixes #11
=> Fixed browsing files history.

src/git.cpp
Ensure the diff content is shown for the first commit by adding "--root" when the
first commit is being displayed.
Fixes issue #47 .
=> Show diff on the first commit

src/git.cpp
Obviously git changed the way how it reports detached branches. Not it reads like this:
`HEAD detached at ccfb057`
This PR fixes the detection in qgit.
=> fixed recognition of detached branches

src/common.h
Fix some C-style casts to not pointlessly strip away `const`-ness. This avoids tripping `-Wcast-qual`.
=> Don't cast away const

src/mainimpl.cpp
When building for QT5.2 and later, use QFontDatabase::systemFont() to
retrieve the default fonts. This fixes two font issues on the MacOS:
* The fonts selected via QApplication::font() are not optimum and
look very pixelated.
* QFont::setStyleHint() doesn't retrieve a valid font though
QFont::setFixedPitch() enforces a fixed pitch. This results in
an unreadable diff view.
=> Fix: Use QFontDatabase::systemFont() for default fonts

src/listview.cpp, src/listview.h
This patch fixes the markers generation when using HiDPI displays. The
previous implementation was mixing real pixels and device independent
pixels values when calculating sizes and spacing.
=> UI: Fix marker generation on HiDPI displays

src/console.ui, src/customaction.ui, src/fileview.ui, src/help.ui, src/mainview.ui, src/settings.ui
Modify UI's to use icons from the system icon theme. (Note: this doesn't remove the resource icons; AFAIK/AFAICT, those will still be used if a theme icon is unavailable.) Also, use QButtonBox where appropriate (which automatically uses appropriate theme icons), and remove some superfluous layouts.
Fixes #13.
=> Use theme icons

src/listview.cpp, src/listview.h, src/mainimpl.cpp
These two commits aim to improve navigation in `ListView`.
1. After filtering, the current index should be kept
2. Using SHIFT + UP/DOWN it's now possible to navigate between commits along branches (if filter-highlighting is not active)
=> navigation improvements

src/settings.ui
This button was doing nothing because its `clicked()` signal was not connected.
=> Settings: Fix external editor browse button

src/mainview.ui
This adds `Shift` to the "Checkout" keyboard shortcut so `Ctrl+C` copies to the clipboard as expected. Fixes #34
=> MainBase: Change "Checkout" shortcut to Ctrl+Shift+C

README.adoc, src/git.cpp, src/mainimpl.cpp, src/mainimpl.h
Add the `--view-file` command line argument. Both `--view-file=foo` and
`--view-file foo` are accepted. (The latter is what `git-cola` needs.)
=> Allow opening a file from the command line (RFE #79)

qgit.appdata.xml
I came across the broken URL via the Ubuntu software manager.
=> Update project URLs to GitHub repo

src/listview.cpp
> Operating System: Kubuntu 19.10
> KDE Plasma Version: 5.17.5
> KDE Frameworks Version: 5.66.0
> Qt Version: 5.12.4
> Kernel Version: 5.3.0-29-generic
> OS Type: 64-bit
> Processors: 4 × Intel® Core™ i7-7500U CPU @ 2.70GHz
> Memory: 15.5 GiB of RAM
It's a Dell XPS laptop running the stock Kubuntu with the KDE backports. My laptop screen is 3200x1800 which I scale 1.5x in the System Settings.
Follow-up of #86, but I now understand what is going on :)
On the master branch, the tag / branch labels are truncated: ![Screenshot_20200207_002728](https://user-images.githubusercontent.com/623458/73990394-e2cc5d00-4940-11ea-9429-35e04fc8d8e4.png)
This is due to the fact `dpr` is systematically cast into an integer prior to the multiplication / division. This essentially rounds down / up fractional …
=> Support for fractional device pixel ratio

qgit.geany, src/mainimpl.cpp, src/myprocess.cpp
I discovered that git config commands qgit invokes do return non-zero exit status.
But, fortunately, in these cases, nothing gets written to stderr.
So, the logic is, if not running windows, produce the command failed dialog only if
exit code != 0  AND  not stderr.empty
I also removed the "Git says:" from the generic command failed dialog text because such commands may not invoke git.   In this case, saying "Git says" will be very misleading.
=> don't rely on STDERR for determining whether command failed

src/mainimpl.cpp, src/mainview.ui
The `Settings` dialog was inaccessible on macOS because its menu item was being removed by Qt's menu role heuristic, and the `Setup actions` menu item took its place.
**Edit:** Amended to now also prevent suitably named custom actions from suffering the same fate as `Setup actions`.
Some screenshots to illustrate the problem and the solution.
No `Settings` item in the `Edit` Menu (expected), `Actions` menu missing when there are no actions:
The `Preferences` item in the application menu is actually the `Setup actions` item, only betrayed by its icon:
`Settings` appears as `Preferences` in the application menu:
`Setup actions` is back in `Actions` where it belongs:
=> Make Settings dialog accessible on macOS

src/common.h, src/filelist.cpp, src/listview.cpp, src/mainimpl.cpp, src/revsview.cpp, src/revsview.h, src/revsview.ui, src/settings.ui, src/settingsimpl.cpp, src/settingsimpl.h
Adds an `Enable drag & drop` toggle to the `Settings` dialog. Defaults to enabled. Fixes #84
=> Make drag & drop functionality optional

src/cache.cpp, src/git.cpp
Avoid corrupting memory by clearing the cache before freeing it's content.
Also adds a bounds check on the sha array.
Fix #69
Fix #71
=> Fix loading of invalid cache file

README.adoc, src/src.pro
Remove linking aginst X11 on MacOS.
Compiled successfully with Qt5 installed with brew.
=> Fix build on MacOS

CMakeLists.txt, src/common.cpp, src/git.cpp, src/listview.cpp, src/mainimpl.cpp, src/qgit.cpp
While Qt4 is unmaintained for several years and itself fails to build
on modern systems, qgit build with Qt4 was broken by commits b68c3e76
and 3f25d12a and no one seems to have noticed in ~two years.
Rather than fix it, it is probably time to clean it up altogether.
This commit does not fix qmake build system which seems to have more
issues, it should probably be dropped as well in favor of CMake.
=> Cleanup Qt4 compatibility, raise Qt minimum to 5.6.0

src/annotate.h, src/common.h, src/dataloader.h, src/git.cpp, src/myprocess.cpp, src/smartbrowse.h
Replace `QTime` by `QElapsedTimer` of Qt >=4.7
Docs:
https://doc.qt.io/qt-5/qelapsedtimer.html
Addresses this compiler warning:
```
warning: ‘void QTime::start()’ is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
```
=> Address compiler warnings about deprecated QTime::start

src/common.h, src/git.cpp, src/inputdialog.cpp, src/listview.cpp, src/mainimpl.cpp, src/myprocess.cpp, src/patchcontent.cpp
Replace `QString::SplitBehavior` by `Qt::SplitBehavior` of Qt >=5.14
Docs:
- https://doc.qt.io/qt-5/qstring.html#split
- https://doc.qt.io/qt-5/qt.html#SplitBehaviorFlags-enum
Addresses this compiler warning:
```
warning: ‘QStringList QString::split(QChar, QString::SplitBehavior, Qt::CaseSensitivity) const’ is deprecated: Use Qt::SplitBehavior variant instead [-Wdeprecated-declarations]
```
=> Address compiler warnings about deprecated QString::SplitBehavior for compiling with Qt >=5.14

CMakeLists.txt
@tibirna just an idea, with a rather conservative new version value for a start (see below), happy to discuss.
Warnings was:
> CMake Deprecation Warning at CMakeLists.txt:8 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
>
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
CMake in the wild is at:
```
Debian oldstable/buster 3.13.4-1
Debian stable/bullseye  3.18.4-2
Gentoo stable           3.20.5
Gentoo unstable         3.21.2
Ubuntu 18.04LTS/bionic  3.10.2-1ubuntu2
Ubuntu 20.04LTS/focal   3.16.3-1ubuntu1
Ubuntu 21.04/hirsute    3.18.4-2ubuntu1
```
=> CMake: Address warning about compatibility with CMake 2.x.x

src/FileHistory.cc, src/FileHistory.h, src/common.h, src/git.cpp, src/git.h, src/listview.cpp, src/revsview.cpp
This is a basic implementation for issue #118.  The hash size is hardcoded to show 8 characters.
=> FileHistory: Add "Short Hash" column.

README.adoc
According to [src/src.pro#L45](https://github.com/SubOptimal/qgit/blob/d1771ba32c5468afee623f0389279a8b66efa854/src/src.pro#L45) the installation directory on Linux is not `$HOME/bin` but rather `QT_INSTALL_BINS`.
The installation directory `~/bin` is used only on MacOS.
=> Amend installation target for MacOS and Linux in the documentation.

src/common.h, src/listview.cpp, src/mainimpl.cpp, src/namespace_def.cpp
Saving Text color (usually black) to use as text color in the commit list.
=> FIX #135 Commit list is not readable with dark colors schema

src/git.cpp
when doing separate and remerge style merge diffs
Fixes #129.
=> Pass --simplify-merges to git log to counteract the change in git 2.36 that disables history simplification

src/git.cpp
Git 2.32 made the behaviour of `git log -m` configurable, with `--diff-merges=separate` merely being the default.
=> Override any log.diffMerges configuration that could spell disaster for file history parsing

.github/workflows/build.yaml, qgit.appdata.xml
Commit 1153238 incorrectly removed the 'type="default"' tag for the default screenshot. Add it back.
Fixes: 1153238 appdata: Add screenshots
---
github/workflows/build: Use Ubuntu 22.04
=> appdata: Re-add default tag to screenshot & CI: Ubuntu 22.04
